name: TikTok Repost Takipçisi

on:
  schedule:
    - cron: '*/5 * * * *'   # 5 dakikada bir
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Kütüphaneleri kur
        run: |
          pip install playwright requests playwright-stealth
          playwright install firefox
      
      - name: Botu çalıştır
        run: python -u main.py
        env:
          TIKTOK_USER: ${{ secrets.TIKTOK_USER }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
